site_name: Кастомный сайт ИТМО
site_description: Современный статический сайт с кастомной темой и автоматизацией
site_url: https://aasemikov.github.io/my-static-site/
site_author: Семиков Алексей
copyright: "Copyright © 2025 Семиков Алексей - Университет ИТМО"

# Кастомная тема на основе Material
theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.suggest
    - toc.integrate
    - content.code.copy
  palette:
    - scheme: default
      primary: custom
      accent: amber
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: custom
      accent: amber
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra_css:
  - stylesheets/custom.css
extra_javascript:
  - javascripts/custom.js

nav:
  - Главная: index.md
  - О проекте: about.md
  - Отчет: report.md
  - Демо: demo.md
  - Технологии: technologies.md

markdown_extensions:
  - toc:
      permalink: true
      permalink_symbol: "🔗"
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - attr_list
  - md_in_html

extra:
  analytics:
    provider: google
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/aasemikov
      name: GitHub репозиторий
    - icon: fontawesome/brands/python
      link: https://python.org
      name: Python
  generator: false

plugins:
  - search
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true