site_name: Мой статический сайт
site_description: Статический сайт на GitHub Pages
site_url: https://aasemikov.github.io/my-static-site/

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - search.suggest

nav:
  - Главная: index.md
  - О проекте: about.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/aasemikov

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite