site_name: Мой статический сайт ИТМО
site_description: Кастомный статический сайт с расширенной функциональностью
site_url: https://aasemikov.github.io/my-static-site/
site_author: Семиков Алексей
copyright: Copyright &copy; 2025 Семиков Алексей - Университет ИТМО

# Кастомная тема на основе Material
theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.tabs
    - navigation.sections
    - search.suggest
    - navigation.expand
    - toc.integrate
  palette:
    - scheme: default
      primary: blue
      accent: amber
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: amber
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

# Дополнительные CSS
extra_css:
  - stylesheets/custom.css

# Дополнительные JS
extra_javascript:
  - javascripts/custom.js

# Навигация
nav:
  - Главная: index.md
  - О проекте: about.md
  - Отчет: report.md
  - Демо: demo.md

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - attr_list
  - md_in_html

plugins:
  - search
  - minify:
      minify_html: true