site_name: Мой статический сайт
site_description: Статический сайт на GitHub Pages
site_url: https://aasemikov.github.io/my-static-site/

theme:
  name: null
  custom_dir: custom_theme/

nav:
  - Главная: index.md
  - О проекте: about.md
  - Отчет Задание 1: report.md
  - Отчет Задание 2: report-lab-2.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/aasemikov

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite