name: Deploy MkDocs

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-css: 
    name: Build CSS
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code
        uses: actions/checkout@v4
      - name: ⎔ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install npm dependencies
        run: npm ci

      - name: Build CSS (development)
        run: npm run build:css

      - name: Build CSS (production)
        run: npm run build:min

      - name: Upload CSS artifacts
        uses: actions/upload-artifact@v4
        with:
          name: css-assets
          path: |
            custom_theme/assets/css/
          retention-days: 1

  build-site:
    name: Build Site
    runs-on: ubuntu-latest
    needs: build-css
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs pymdown-extensions

      - name: Download CSS artifacts
        uses: actions/download-artifact@v4
        with:
          name: css-assets
          path: custom_theme/assets/css/

      - name: Build site with MkDocs
        run: mkdocs build

      - name: Upload site artifacts
        uses: actions/upload-artifact@v4
        with:
          name: built-site
          path: site/
          retention-days: 1

  minify-html:
    name: Minify HTML
    runs-on: ubuntu-latest
    needs: build-site
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install npm dependencies
        run: npm ci

      - name: Download site artifacts
        uses: actions/download-artifact@v4
        with:
          name: built-site
          path: site/

      - name: Minify HTML
        run: npm run build:html

      - name: Upload minified site
        uses: actions/upload-artifact@v4
        with:
          name: minified-site
          path: site/
          retention-days: 1

  validate-html:
    name: Validate HTML
    runs-on: ubuntu-latest
    needs: build-site
    if: always()
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install npm dependencies
        run: npm ci

      - name: Download site artifacts
        uses: actions/download-artifact@v4
        with:
          name: built-site
          path: site/

      - name: Validate HTML
        run: npm run validate
        continue-on-error: true

      - name: Upload validation report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: validation-report
          path: |
            site/**/*.html
          retention-days: 7

  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: [build-site, minify-html]
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    
    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download minified site artifacts
        uses: actions/download-artifact@v4
        with:
          name: minified-site
          path: ./site

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './site'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4